"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(t_$e)djiv%k4(e8mc&^$!dlerw4$-f58@$qsaju2_i9rd@j4p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'board',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# config/settings.py

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'kcqt77',                # 이미지 하단에 보이는 DB 이름
        'USER': 'kcqt77',      # 보통 kcqt77 일 가능성이 높습니다
        'PASSWORD': 'a9465518*',
        'HOST': 'sql19-103.cafe24.com',
        'PORT': '',                      # MSSQL 기본포트 1433 (비워두면 자동인식)
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server', # 설치된 드라이버 버전에 맞게 수정
        },
    }
}
# /*$host = '221.155.228.179';
# $port = '3306';
# $db = 'kcqt_qyalit';
# $user = 'kcqt_kyj';
# $pass = '1977519';
# $charset = 'utf8mb4';
# */



# /*$host = "sql19-103.cafe24.com";    //호스트 주소
# $db = "kcqt77";   //데이타베이스 이름
# $user = "kcqt77";      // 기본값 (설정에 따라 다를 수 있음)
# $pass = "a9465518*";          // 기본값 (비밀번호가 있다면 입력)
# $charset = "utf8mb4";    //문자인코딩
# */

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]

# 로그인이 성공하면 메인 페이지('/')로 가라는 설정입니다.
LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/'
